version: '3.9'
services:
    email_backend_service:
      build: .
      volumes:
        - .:/app
      command: 'php artisan serve --host=0.0.0.0'
      depends_on:
      - db
    email_queue_service:
      build: .
      volumes:
        - .:/app
      command: 'php artisan queue:work'
      depends_on:
      - db
    db:
      image: mysql:latest
      restart: unless-stopped
      tty: true
      ports:
        - "33066:3306"
      volumes:
        - ./storage/dbdata:/var/lib/mysql
      environment:
        MYSQL_DATABASE: email_service_database
        MYSQL_USER: abdelrhman
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root
        SERVICE_TAGS: dev
        SERVICE_NAME: mysql
    redis:
      image: redis:latest
      ports:
      - 6371:6379
